export const speciesData = [
  {
    title: "Striped Bass",
    species: "Striped Bass",
    aliases: ["Striper", "Stripper"]
  },
  {
    title: "Surfperch (unknown)",
    species: "Surfperch (unknown)",
    aliases: ['Surfperch', 'Surf Perch']
  },
  {
    title: "Halibut",
    species: "Halibut",
    aliases: ['Butt', 'Flattie', 'Barn Door']
  },
  {
    title: "Leopard Shark",
    species: "Leopard Shark",
    aliases: ['Leopard']
  },
  {
    title: "Tuna (unknown)",
    species: "Tuna (unknown)",
    aliases: []
  },
  {
    title: "Albacore Tuna",
    species: "Albacore Tuna",
    aliases: ["Albie"]
  },
  {
     title: "Bigeye Tuna",
     species: "Bigeye Tuna",
     aliases: ["Big Eye tuna"]
  },
  {"title":"Barred sand bass","species":"Barred sand bass","aliases":[]},
  {"title":"Barred surfperch","species":"Barred surfperch","aliases":[]},
  {"title":"Bat ray","species":"Bat ray","aliases":[]},
  {"title":"Bigeye tuna","species":"Bigeye tuna","aliases":[]},
  {"title":"Black rockfish","species":"Black rockfish","aliases":[]},
  {"title":"Blue rockfish","species":"Blue rockfish","aliases":[]},
  {"title":"Blue shark","species":"Blue shark","aliases":[]},
  {"title":"Bluefin tuna","species":"Bluefin tuna","aliases":[]},
  {"title":"Bocaccio","species":"Bocaccio","aliases":[]},
  {"title":"Bonito shark","species":"Bonito shark","aliases":[]},
  {"title":"Brown smoothhound","species":"Brown smoothhound","aliases":[]},
  {"title":"Cabezon","species":"Cabezon","aliases":[]},
  {"title":"Calico Bass","species":"Calico Bass","aliases":[]},
  {"title":"California barracuda","species":"California barracuda","aliases":[]},
  {"title":"California corbina","species":"California corbina","aliases":[]},
  {"title":"California grunion","species":"California grunion","aliases":[]},
  {"title":"California lizardfish","species":"California lizardfish","aliases":[]},
  {"title":"California sheephead","species":"California sheephead","aliases":[]},
  {"title":"Canary rockfish","species":"Canary rockfish","aliases":[]},
  {"title":"Chilipepper","species":"Chilipepper","aliases":[]},
  {"title":"Chinook salmon","species":"Chinook salmon","aliases":[]},
  {"title":"Coho salmon","species":"Coho salmon","aliases":[]},
  {"title":"Common thresher shark","species":"Common thresher shark","aliases":[]},
  {"title":"Copper rockfish","species":"Copper rockfish","aliases":[]},
  {"title":"Cowcod","species":"Cowcod","aliases":[]},
  {"title":"Giant kelpfish","species":"Giant kelpfish","aliases":[]},
  {"title":"Giant sea bass","species":"Giant sea bass","aliases":[]},
  {"title":"Gray smoothhound","species":"Gray smoothhound","aliases":[]},
  {"title":"Greenspotted rockfish","species":"Greenspotted rockfish","aliases":[]},
  {"title":"Green sturgeon","species":"Green sturgeon","aliases":[]},
  {"title":"Halfmoon","species":"Halfmoon","aliases":[]},
  {"title":"Jack mackerel","species":"Jack mackerel","aliases":[]},
  {"title":"Jacksmelt","species":"Jacksmelt","aliases":[]},
  {"title":"Kelp bass","species":"Kelp bass","aliases":[]},
  {"title":"Kelp greenling","species":"Kelp greenling","aliases":[]},
  {"title":"King salmon","species":"King salmon","aliases":[]},
  {"title":"Lingcod","species":"Lingcod","aliases":[]},
  {"title":"Longfin sanddab","species":"Longfin sanddab","aliases":[]},
  {"title":"Pacific bonito","species":"Pacific bonito","aliases":[]},
  {"title":"Pacific hake","species":"Pacific hake","aliases":[]},
  {"title":"Pacific halibut","species":"Pacific halibut","aliases":[]},
  {"title":"Pacific mackerel","species":"Pacific mackerel","aliases":[]},
  {"title":"Pacific sanddab","species":"Pacific sanddab","aliases":[]},
  {"title":"Pacific staghorn sculpin","species":"Pacific staghorn sculpin","aliases":[]},
  {"title":"Pacific tomcod","species":"Pacific tomcod","aliases":[]},
  {"title":"Pacific whiting","species":"Pacific whiting","aliases":[]},
  {"title":"Petrale sole","species":"Petrale sole","aliases":[]},
  {"title":"Redtail surfperch","species":"Redtail surfperch","aliases":[]},
  {"title":"Rockfish widow","species":"Rockfish widow","aliases":[]},
  {"title":"Roncador stearnsii","species":"Roncador stearnsii","aliases":[]},
  {"title":"Round stingray","species":"Round stingray","aliases":[]},
  {"title":"Rubberlip seaperch","species":"Rubberlip seaperch","aliases":[]},
  {"title":"Sablefish","species":"Sablefish","aliases":[]},
  {"title":"Sargo","species":"Sargo","aliases":[]},
  {"title":"Sculpin","species":"Sculpin","aliases":[]},
  {"title":"Seriola dorsalis","species":"Seriola dorsalis","aliases":[]},
  {"title":"Seriola lalandi","species":"Seriola lalandi","aliases":[]},
  {"title":"Seriphus politus","species":"Seriphus politus","aliases":[]},
  {"title":"Shiner perch","species":"Shiner perch","aliases":[]},
  {"title":"Shortfin mako","species":"Shortfin mako","aliases":[]},
  {"title":"Shovelnose guitarfish","species":"Shovelnose guitarfish","aliases":[]},
  {"title":"Silver salmon","species":"Silver salmon","aliases":[]},
  {"title":"Silver surfperch","species":"Silver surfperch","aliases":[]},
  {"title":"Skipjack","species":"Skipjack","aliases":[]},
  {"title":"Spiny dogfish","species":"Spiny dogfish","aliases":[]},
  {"title":"Spotfin croaker","species":"Spotfin croaker","aliases":[]},
  {"title":"Spotted sand bass","species":"Spotted sand bass","aliases":[]},
  {"title":"Starry flounder","species":"Starry flounder","aliases":[]},
  {"title":"Starry rockfish","species":"Starry rockfish","aliases":[]},
  {"title":"Stereolepis gigas","species":"Stereolepis gigas","aliases":[]},
  {"title":"Striped marlin","species":"Striped marlin","aliases":[]},
  {"title":"Swordfish","species":"Swordfish","aliases":[]},
  {"title":"Vermilion rockfish","species":"Vermilion rockfish","aliases":[]},
  {"title":"Walleye surfperch","species":"Walleye surfperch","aliases":[]},
  {"title":"White croaker","species":"White croaker","aliases":[]},
  {"title":"White seabass","species":"White seabass","aliases":[]},
  {"title":"White sturgeon","species":"White sturgeon","aliases":[]},
  {"title":"Widow rockfish","species":"Widow rockfish","aliases":[]},
  {"title":"Yellowfin croaker","species":"Yellowfin croaker","aliases":[]},
  {"title":"Yellowfin tuna","species":"Yellowfin tuna","aliases":[]},
  {"title":"Yellowtail","species":"Yellowtail","aliases":[]},
  {"title":"Yellowtail rockfish","species":"Yellowtail rockfish","aliases":[]}
];